plugins:
  - jekyll-feed

# For RSS feed, keep in sync with index.html meta
title: Open Path by Chad Whitacre
excerpt: "A Blog About Open Source, Tech, and Society"
author: Chad Whitacre

sass:
  sass_dir: .
exclude:
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "bin"
permalink: /:year/:title/
defaults:
  - values:
      layout: "post"
